#include <stdio.h>
#include "TokenStream.hpp"

int main(int cnt, char *args[]) {
    const char *test_str =
        //--- operators and punctuation
            ": :: ~ ~= % %= ^ ^= & &= - -> -- -= + += ++ "
            "* *= | || |= / /= ! != = == > >> >= >>= < <= << <<="
            "# ( ) [ ] \\ { } ; , . ? "
            "` @ $"

        //--- comments
            "/*one line comment*/\n"
            "/*multi-\n//line\ncomment*/\n"
            "/*comment/*within //comment*/\n"
            "/* abcdefghijklmnopqrstuvwxyz 0123456789 */\n"
            "/*abcdefghijklmnopqrstuvwxyz */"
            "/*0123456789ABCDEF0123456789ABCDEF */\n"
            "/**//* */\n/**/"
            "//abcdefghijklmnopqrstuvwxyz \n"

        //--- numbers
            "0 0b1010010001111001100111 0123274127546312 12304823876239012938409813 0x123456789ABCDEF "
            "-0 -0b101 -0123 -123 -0x01'23'456789abcdef "
            "+0 +0b101 +0123 +123 +0x01'23'456789abcdef "
            "123.1 123.0001 12'3.00'01 "
            "123.1 z -123.1 z +123.1 z 1.234e1 z -1.234e1 z +1.234e1 z 1.234e-1 z -1.234e-1 z +1.234e+1 z"
            "-123.1 -123.0001 +123.1 +123.0001 "
            "123e789 123e-789 123e+789 "
            "0123.e1 0123.e-1 0123.e+1 "
            "0123.012e1 0123.012e-1 0123.012e+1 "

        //---
            "    void TokenStream::getWhiteSpace(void) {\n"
            "        EToken etoken = (stream.isEOF()? eEOF: eEmpty);\n"
            "        char tmps[1000];\n"
            "        uint index = 0;\n"
            "        if ( stream.isSpace() ) {\n"
            "            while ( index < sizeof(tmps)  &&  !stream.isEOF()  &&  stream.isSpace() ) {\n"
            "                tmps[index++] = stream.current();\n"
            "                stream.next();\n"
            "            }\n"
            "            etoken = eSpace;\n"
            "\n"
            "        } else if ( stream.peek(\"//\") ) {\n"
            "            tmps[index++] = stream.current();\n"
            "            tmps[index++] = stream.next();\n"
            "            while ( !stream.isEOF() ) {\n"
            "                tmps[index++] = stream.next();\n"
            "                if ( stream.isEOL()  ||  stream.isEOF() ) {\n"
            "                    stream.next();\n"
            "                    break;\n"
            "                }\n"
            "            }\n"
            "            etoken = eComment;\n"
            "\n"
            "        } else if ( stream.peek(\"/*\") ) {\n"
            "            tmps[index++] = stream.current();\n"
            "            tmps[index++] = stream.next();\n"
            "            tmps[index++] = stream.next();\n"
            "            stream.next();\n"
            "            while ( !stream.isEOF() ) {\n"
            "                // tmps[index++] = stream.current();\n"
            "                if ( stream.peek(\"*/\") ) {\n"
            "                    tmps[index++] = stream.current();\n"
            "                    tmps[index++] = stream.next();\n"
            "                    stream.next();\n"
            "                    break;\n"
            "                }\n"
            "                tmps[index++] = stream.current();\n"
            "                stream.next();\n"
            "            }\n"
            "            etoken = eComment;\n"
            "        }\n"
            "\n"
            "        tmps[index++] = 0;\n"
            "        // etoken = (stream.isEOF()? eEOF: (tmps[0] != 0? eSpace: eEmpty));\n"
            "        current_token = Token(etoken, tmps);\n"
            "    }\n"
            "    void TokenStream::getIdentifier(void) {\n"
            "        char tmps[200];\n"
            "        uint index = 0;\n"
            "        tmps[index++] = stream.current();\n"
            "        while ( isalnum(stream.next())  ||  stream.current() == '_' ) {\n"
            "            tmps[index++] = stream.current();\n"
            "        }\n"
            "        tmps[index] = 0;\n"
            "        current_token = Token(eWord, tmps);\n"
            "    }\n"
            "    void TokenStream::getNumber(void) {\n"
            "        char tmps[200];\n"
            "        uint index = 0;\n"
            "        tmps[index++] = stream.current();\n"
            "        while ( isdigit(stream.next()) ) {\n"
            "            tmps[index++] = stream.current();\n"
            "        }\n"
            "        if ( stream.current() == '.' ) {\n"
            "            tmps[index++] = stream.current();\n"
            "            if ( isdigit(stream.next()) ) {\n"
            "                tmps[index++] = stream.current();\n"
            "                while ( isdigit(stream.next()) ) {\n"
            "                    tmps[index++] = stream.current();\n"
            "                }\n"
            "            }\n"
            "        }\n"
            "        if ( stream.current() == 'e'  ||  stream.current() == 'E' ) {\n"
            "            tmps[index++] = stream.current();\n"
            "            stream.next();\n"
            "            if ( stream.current() == '-'  ||  stream.current() == '+' ) {\n"
            "                tmps[index++] = stream.current();\n"
            "                stream.next();\n"
            "            }\n"
            "            if ( isdigit(stream.current()) ) {\n"
            "                tmps[index++] = stream.current();\n"
            "                while ( isdigit(stream.next()) ) {\n"
            "                    tmps[index++] = stream.current();\n"
            "                }\n"
            "            }\n"
            "        }\n"
            "        tmps[index] = 0;\n"
            "        current_token = Token(eNumber, tmps);\n"
            "    }\n"
            "    void TokenStream::getString(void) {\n"
            "        char tmps[1000];\n"
            "        uint index = 0;\n"
            "        char end_of_string = stream.current();\n"
            "        tmps[index++] = stream.current();\n"
            "        while ( !(stream.isEOF()  ||  stream.next() == end_of_string) ) {\n"
            "            tmps[index++] = stream.current();\n"
            "            stream.next();\n"
            "        }\n"
            "        tmps[index++] = stream.current();\n"
            "        tmps[index] = 0;\n"
            "        current_token = Token(eString, tmps);\n"
            "    }\n"
            "    TokenStream::Token TokenStream::next(void) {\n"
            "        current_token = Token(eEOF);\n"
            "        getWhiteSpace();\n"
            "        if ( current_token.isEmpty() ) {\n"
            "            if ( current_token.isEOF() ) {\n"
            "                current_token = Token(eEOF);\n"
            "                return current_token;\n"
            "\n"
            "            } else if ( isalpha(stream.current())  ||  stream.current() == '_' ) {\n"
            "                getIdentifier();\n"
            "\n"
            "            } else if ( isdigit(stream.current()) ) {\n"
            "                getNumber();\n"
            "\n"
            "            } else if ( stream.current() == '\\\''  ||  stream.current() == '\"' ) {\n"
            "                getString();\n"
            "\n"
            "            } else {\n"
            "                switch ( stream.current() ) {\n"
            "                    case '`':\n"
            "                    case '@':\n"
            "                    case '#':\n"
            "                    case '$':\n"
            "                    case '(':\n"
            "                    case ')':\n"
            "                    case '[':\n"
            "                    case ']':\n"
            "                    case '\\\\':\n"
            "                    case '{':\n"
            "                    case '}':\n"
            "                    case ';':\n"
            "                    case ',':\n"
            "                    case '.':\n"
            "                    case '?': current_token = Token(stream.current()); break;\n"
            "\n"
            "                    case ':':\n"
            "                        if ( stream.peek(1) == ':' ) {\n"
            "                            current_token = Token(eNameResolution);\n"
            "                            stream.next();\n"
            "                        } else {\n"
            "                            current_token = Token(eColon);\n"
            "                        }\n"
            "                        break;\n"
            "                    case '~':\n"
            "                        if ( stream.peek(1) == '=' ) {\n"
            "                            current_token = Token(eBitwiseNotEquals);\n"
            "                            stream.next();\n"
            "                        } else {\n"
            "                            current_token = Token(eBitwiseNot);\n"
            "                        }\n"
            "                        break;\n"
            "                    case '%':\n"
            "                        if ( stream.peek(1) == '=' ) {\n"
            "                            current_token = Token(eModulusEquals);\n"
            "                            stream.next();\n"
            "                        } else {\n"
            "                            current_token = Token(eModulus);\n"
            "                        }\n"
            "                        break;\n"
            "                    case '^':\n"
            "                        if ( stream.peek(1) == '=' ) {\n"
            "                            current_token = Token(eBitwiseXorEquals);\n"
            "                            stream.next();\n"
            "                        } else {\n"
            "                            current_token = Token(eBitwiseXor);\n"
            "                        }\n"
            "                        break;\n"
            "                    case '&':\n"
            "                        if ( stream.peek(1) == '=' ) {\n"
            "                            current_token = Token(eBitwiseAndEquals);\n"
            "                            stream.next();\n"
            "                        } else if ( stream.peek(1) == '&' ) {\n"
            "                            current_token = Token(eBooleanAnd);\n"
            "                            stream.next();\n"
            "                        } else {\n"
            "                            current_token = Token(eBitwiseAnd);\n"
            "                        }\n"
            "                        break;\n"
            "                    case '-':\n"
            "                        if ( stream.peek(1) == '=' ) {\n"
            "                            current_token = Token(eMinusEquals);\n"
            "                            stream.next();\n"
            "                        } else if ( stream.peek(1) == '-' ) {\n"
            "                            current_token = Token(eDecrement);\n"
            "                            stream.next();\n"
            "                        } else {\n"
            "                            current_token = Token(eMinus);\n"
            "                        }\n"
            "                        break;\n"
            "                    case '+':\n"
            "                        if ( stream.peek(1) == '=' ) {\n"
            "                            current_token = Token(eSumEquals);\n"
            "                            stream.next();\n"
            "                        } else if ( stream.peek(1) == '+' ) {\n"
            "                            current_token = Token(eIncrement);\n"
            "                            stream.next();\n"
            "                        } else {\n"
            "                            current_token = Token(eSum);\n"
            "                        }\n"
            "                        break;\n"
            "                    case '*':\n"
            "                        if ( stream.peek(1) == '=' ) {\n"
            "                            current_token = Token(eMultiplyEquals);\n"
            "                            stream.next();\n"
            "                        } else {\n"
            "                            current_token = Token(eMultiply);\n"
            "                        }\n"
            "                        break;\n"
            "                    case '|':\n"
            "                        if ( stream.peek(1) == '=' ) {\n"
            "                            current_token = Token(eBitwiseOrEquals);\n"
            "                            stream.next();\n"
            "                        } else if ( stream.peek(1) == '|' ) {\n"
            "                            current_token = Token(eBooleanOr);\n"
            "                            stream.next();\n"
            "                        } else {\n"
            "                            current_token = Token(eBitwiseOr);\n"
            "                        }\n"
            "                        break;\n"
            "                    case '/':\n"
            "                        if ( stream.peek(1) == '=' ) {\n"
            "                            current_token = Token(eDivideEquals);\n"
            "                            stream.next();\n"
            "                        } else {\n"
            "                            current_token = Token(eDivide);\n"
            "                        }\n"
            "                        break;\n"
            "                    case '!':\n"
            "                        if ( stream.peek(1) == '=' ) {\n"
            "                            current_token = Token(eNotEqualTo);\n"
            "                            stream.next();\n"
            "                        } else {\n"
            "                            current_token = Token(eBooleanNot);\n"
            "                        }\n"
            "                        break;\n"
            "                    case '=':\n"
            "                        if ( stream.peek(1) == '=' ) {\n"
            "                            current_token = Token(eEqualTo);\n"
            "                            stream.next();\n"
            "                        } else {\n"
            "                            current_token = Token(eEquals);\n"
            "                        }\n"
            "                        break;\n"
            "                    case '<':\n"
            "                        if ( stream.peek(1) == '=' ) {\n"
            "                            current_token = Token(eLessEqualTo);\n"
            "                            stream.next();\n"
            "                        } else if ( stream.peek(1) == '<' ) {\n"
            "                            stream.next();\n"
            "                            if ( stream.peek(1) == '=' ) {\n"
            "                                current_token = Token(eShiftLeftAssign);\n"
            "                                stream.next();\n"
            "                            } else {\n"
            "                                current_token = Token(eShiftLeft);\n"
            "                            }\n"
            "                        } else {\n"
            "                            current_token = Token(eLessThan);\n"
            "                        }\n"
            "                        break;\n"
            "                    case '>':\n"
            "                        if ( stream.peek(1) == '=' ) {\n"
            "                            current_token = Token(eGreaterEqualTo);\n"
            "                            stream.next();\n"
            "                        } else if ( stream.peek(1) == '>' ) {\n"
            "                            stream.next();\n"
            "                            if ( stream.peek(1) == '=' ) {\n"
            "                                current_token = Token(eShiftRightAssign);\n"
            "                                stream.next();\n"
            "                            } else {\n"
            "                                current_token = Token(eShiftRight);\n"
            "                            }\n"
            "                        } else {\n"
            "                            current_token = Token(eGreaterThan);\n"
            "                        }\n"
            "                        break;\n"
            "                }\n"
            "                stream.next();\n"
            "            }\n"
            "        }\n"
            "        return current_token;\n"
            "    }\n"
            "/*1234567890\n"
            "           \n"
        ;

    Parser::TokenStream stream(test_str);
    Parser::TokenStream::Token token;
    Tools::String acc;
    while ( !(token = stream.next()).isEOF() ) {
        fprintf(stderr, "{%s, %c}\n", token.text.GetText(), token.token_enum);
        acc += token.text;
    }
    fprintf(stderr, "%s\n", test_str);
    fprintf(stderr, "%s\n%s\n", acc.GetText(), (acc != test_str? "FAILED": "passed") );
}
